services:
  postgres:
    image: postgres:latest
    container_name: grapy_postgres
    environment:
      POSTGRES_USER: grapy_user
      POSTGRES_PASSWORD: grapy_password
      POSTGRES_DB: grapy_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U grapy_user"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - grapy_network

volumes:
  postgres_data:
    driver: local

networks:
  grapy_network:
    driver: bridge
